#!/bin/sh
# Generate inc/build_info.h from git metadata.
# If git is unavailable or .git is missing, exits silently so the
# fallback header (build_info_fallback.h) is used instead.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_DIR="${1:-${REPO_ROOT}/inc}"
OUTPUT_FILE="${OUTPUT_DIR}/build_info.h"

# If git is not installed or this is not a git repo, skip generation.
if ! command -v git >/dev/null 2>&1; then
    exit 0
fi

if ! git -C "${REPO_ROOT}" rev-parse --git-dir >/dev/null 2>&1; then
    exit 0
fi

BUILD_ID="$(git -C "${REPO_ROOT}" describe --tags --always --dirty 2>/dev/null || echo "unknown")"
GIT_HASH="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo "unknown")"

CONTENT="/*
 * Auto-generated by scripts/gen_build_info.sh — do not edit.
 */

#ifndef PROJECT_BUILD_INFO_H
#define PROJECT_BUILD_INFO_H

#define PROJECT_BUILD_ID \"${BUILD_ID}\"
#define PROJECT_GIT_HASH \"${GIT_HASH}\"

#endif /* PROJECT_BUILD_INFO_H */
"

# Only overwrite if content changed (avoids unnecessary rebuilds).
if [ -f "${OUTPUT_FILE}" ]; then
    OLD_CONTENT="$(cat "${OUTPUT_FILE}")"
    if [ "${OLD_CONTENT}" = "${CONTENT}" ]; then
        exit 0
    fi
fi

mkdir -p "${OUTPUT_DIR}"
TMPFILE="$(mktemp "${OUTPUT_DIR}/build_info.h.XXXXXX")"
printf '%s' "${CONTENT}" > "${TMPFILE}"
mv -f "${TMPFILE}" "${OUTPUT_FILE}"
