# GenerateBuildInfo.cmake — called at build time via add_custom_target.
# Generates inc/build_info.h from git metadata.
# If git queries fail, the file is not written and the fallback header is used.

execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --tags --always --dirty
    WORKING_DIRECTORY "${REPO_DIR}"
    OUTPUT_VARIABLE BUILD_ID
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_DESCRIBE_RESULT
    ERROR_QUIET
)

execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
    WORKING_DIRECTORY "${REPO_DIR}"
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_REVPARSE_RESULT
    ERROR_QUIET
)

if(NOT GIT_DESCRIBE_RESULT EQUAL 0)
    set(BUILD_ID "unknown")
endif()
if(NOT GIT_REVPARSE_RESULT EQUAL 0)
    set(GIT_HASH "unknown")
endif()

set(CONTENT "\
/*
 * Auto-generated by cmake/GenerateBuildInfo.cmake — do not edit.
 */

#ifndef PROJECT_BUILD_INFO_H
#define PROJECT_BUILD_INFO_H

#define PROJECT_BUILD_ID \"${BUILD_ID}\"
#define PROJECT_GIT_HASH \"${GIT_HASH}\"

#endif /* PROJECT_BUILD_INFO_H */
")

# Only overwrite if content changed (avoids unnecessary rebuilds).
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" OLD_CONTENT)
    if("${OLD_CONTENT}" STREQUAL "${CONTENT}")
        return()
    endif()
endif()

file(WRITE "${OUTPUT_FILE}" "${CONTENT}")
